export const projects = [
  {
    shortTitle: "firebase-budget-tracker",
    imageSrc: "projectsThumbnails/firebase-budget-tracker.png",
    staticPathImportName: "firebase",
    alt: "firebase-budget-tracker",
    fullTitle: "Budget Tracker - Firebase",
    demoHref: "https://ivanmpr.github.io/firebase-budget-tracker/",
    codeHref: "https://github.com/IvanMPR/firebase-budget-tracker",
    description: `React CRUD app with implemented Firebase database and authentication, styled with Tailwind CSS. You can add, edit, delete and filter your expenses... `,
    projectNum: 0,
    techStack: ["react", "firebase", "tailwind"],
  },
  {
    shortTitle: "nodejs-portfolio",
    imageSrc: "projectsThumbnails/portfolio.png",
    staticPathImportName: "portfolio",
    alt: "nodejs-portfolio",
    fullTitle: "this",
    demoHref: "https://ivanmiceta.dev",
    codeHref: "https://github.com/IvanMPR/react-portfolio",
    description: `...is the website you're currently browsing. It is created using React and Sass, it is responsive, and for the sake of learning, everything is built from scratch...`,
    projectNum: 1,
    techStack: ["react", "nextjs", "tailwind"],
  },
  {
    shortTitle: "lines",
    imageSrc: "projectsThumbnails/lines.jpg",
    staticPathImportName: "lines",
    alt: "Lines game",
    fullTitle: "Lines game",
    demoHref: "https://ivanmpr.github.io/Lines-FULL/",
    codeHref: "https://github.com/IvanMPR/Lines-FULL",
    description: `BFS algo. Select he ball by clicking on it. Click on the any empty field to place the ball. Make a line of 5 or more consecutive balls of the same
     color (in a row, column or diagonally), in order to clear them
     of the board and earn points...`,
    projectNum: 2,
    techStack: ["html", "css", "js", "illustrator"],
  },
  {
    shortTitle: "BFS",
    imageSrc: "projectsThumbnails/bfs.jpg",
    staticPathImportName: "bfs",
    alt: "Breadth first search algo",
    fullTitle: "BFS and shortest path algo",
    demoHref: "https://ivanmpr.github.io/BFS/",
    codeHref: "https://github.com/IvanMPR/BFS",
    description: `BFS algo. Place the start and end points, place the walls optionally, and click on the Start button. The shortest path will be shown...`,
    projectNum: 3,
    techStack: ["html", "css", "js"],
  },
  {
    shortTitle: "memory",
    imageSrc: "projectsThumbnails/memory-online.jpg",
    staticPathImportName: "memory",
    alt: "Memory Multiplayer game",
    fullTitle: "Memory Multiplayer",
    demoHref: "https://multiplayer-memory-game.onrender.com",
    codeHref: "https://github.com/IvanMPR/memory-multiplayer",
    description: `Online two player Memory Game, created using NodeJS, Express and Socket.io. Deployed on Render.com.   Might take a while to load, be patient please...`,
    projectNum: 4,
    techStack: ["html", "css", "js", "nodejs", "express", "socketio"],
  },
  {
    shortTitle: "tic-tac-toe",
    imageSrc: "projectsThumbnails/tic-tac-toe.jpg",
    staticPathImportName: "tic-tac-toe",
    alt: "Tic Tac Toe game",
    fullTitle: "Tic Tac Toe",
    demoHref: "https://tic-tac-toe-online-multiplayer-game.onrender.com",
    codeHref: "https://github.com/IvanMPR/tic-tac-toe",
    description: `Online multiplayer game of Tic Tac Toe, created using NodeJS,
         Express and Socket.io. Deployed on Render.com. Might take a while to load, be patient please...`,
    projectNum: 5,
    techStack: ["html", "css", "js", "nodejs", "express", "socketio"],
  },
  {
    shortTitle: "shooting",
    imageSrc: "projectsThumbnails/shooting.jpg",
    staticPathImportName: "shooting",
    alt: "Shooting game",
    fullTitle: "Shooting game",
    demoHref: "https://ivanmpr.github.io/Whack-a-Mole/",
    codeHref: "https://github.com/IvanMPR/Whack-a-Mole",
    description: `Click on the Start button, and after short music intro, targets will
                appear randomly on their spots. Earned points depends on your
                precision. 'Green' circle is 'Bullseye', and it brings 12 points...`,
    projectNum: 6,
    techStack: ["html", "css", "js", "illustrator"],
  },
  {
    shortTitle: "weather",
    imageSrc: "projectsThumbnails/weather.jpg",
    staticPathImportName: "weather",
    alt: "Weather app",
    fullTitle: "Weather app",
    demoHref: "https://ivanmpr.github.io/Weather-app/",
    codeHref: "https://github.com/IvanMPR/Weather-app",
    description: `Weather app is responsive, and works behind the scene with two
       third party API-s...`,
    projectNum: 7,
    techStack: ["html", "css", "js"],
  },
  {
    shortTitle: "quiz",
    imageSrc: "projectsThumbnails/flags.jpg",
    staticPathImportName: "flags",
    alt: "Guess the flag quiz",
    fullTitle: "Guess the Flag Quiz",
    demoHref: "https://ivanmpr.github.io/Guess-the-Flag-FV/",
    codeHref: "https://github.com/IvanMPR/Guess-the-Flag-FV",
    description: `This is a fun quiz app where you can learn almost every flag
       that is used in the world today! You can play in three different
       languages...`,
    projectNum: 8,
    techStack: ["html", "css", "js"],
  },
  {
    shortTitle: "europe",
    imageSrc: "projectsThumbnails/map.jpg",
    staticPathImportName: "map",
    alt: "European countries map",
    fullTitle: "European countries",
    demoHref: "https://ivanmpr.github.io/Europe-Map-Project/",
    codeHref: "https://github.com/IvanMPR/Europe-Map-Project",
    description: `Click on the random country in the map of Europe and you will
       get all basic data about that state in the container on the left
       side of the screen...`,
    projectNum: 9,
    techStack: ["html", "css", "js"],
  },

  {
    shortTitle: "hangman",
    imageSrc: "projectsThumbnails/hangman.jpg",
    staticPathImportName: "hangman",
    alt: "Hangman game",
    fullTitle: "Hangman game",
    demoHref: "https://ivanmpr.github.io/Hangman-game/",
    codeHref: "https://github.com/IvanMPR/Hangman-game",
    description: `The goal of the game is to guess the hidden country name. Player has max of 10 attempts. For every miss, one additional part of the body is hanged...`,
    projectNum: 10,
    techStack: ["html", "css", "js"],
  },
];

export const projectsLength = projects.length;
